### ISSUE TITLE
acces only to part of tag array

### ISSUE THREAD

**Issue by landercillo** [ruscito/pycomm#20]
Hi.
First, sorry for my english and thanks for this script. It´s fantastic. Ok, my question, ¿is there any form to acces to part of the read_array?.
If i want to read the data of a tag like N30_VIT  wich has a length of 255 and i only need to read the position from 30 to 60 i must to read from 0 to 60 at least.

It will be fine that we can acces directly to the position and lenght that we need.

Something like this:

read_array_len(N30_VIT, 30, 60).

Thanks for all.

**Comment by ruscito** [comment]
@landercillo this is a good suggestion I will put in my list of things to do :)
