### ISSUE TITLE
method close() may not __sock.close() on exception

### ISSUE THREAD

**Issue by gman8a** [ruscito/pycomm#22]
I am not sure if this is a bug, but I think so.

The close() method may not close the socket when an exception occurs before the __sock.close() call
Maybe this code is better:

    def close(self):
        """
        socket close
        :return: true if no error otherwise false
        """
        errStr = ''
        try:
            if self._target_is_connected:
                self.forward_close()
            if self._session != 0:
                self.un_register_session()

        except Exception as e:
            print "Error on close() -> session Err: %s" % e.message
            # http://stackoverflow.com/questions/7075200/converting-exception-to-a-string-in-python-3
            errStr += "Error {0}".format(str(e.args[0])).encode("utf-8")

        # %GLA must do a cleanup __sock.close()
        try:
            if self.__sock:
                self.__sock.close()

        except Exception as e:
            print "close() -> __sock.close Err: %s" % e.message
            errStr += "; Error {0}".format(str(e.args[0])).encode("utf-8")

        self.clean_up()

        if errStr:
            raise CommError(errStr)

**Comment by ruscito** [comment]
@gman8a I have updated the close function. Thanks for the help
