### ISSUE TITLE
SLC connection

### ISSUE THREAD

**Issue by cldodd** [ruscito/pycomm#3]
Not an issue but cannot understand how to connect retrieve data from Micrologix, CLX works a treat but unsure of SLC address format for tag read. Great work, this is a very tidy and simple implementation for a novice coder like me.
Chris.

**Comment by ruscito** [comment]
Chris SLC reading is not 100% completed. The reading and write methods work fine, but I need to implement the method parsing, so at the moment the tag is hard-coded in the read/write method. I'm super busy with a commissioning right now, but  I will try to work on this in the next weeks. I will keep you posted.
