### ISSUE TITLE
Concurrent connections on L33ER

### ISSUE THREAD

**Issue by crushndent** [ruscito/pycomm#35]
Using two programs that both connect to L33ER causes a timeout error on read_tags().
**Code:**
from abpycomm.ab_comm.clx import Driver as ClxDriver
from time import sleep
PLC_IP = '192.168.100.110'
driver = ClxDriver()
driver.open(PLC_IP)
tag = ['MANUAL_LT']
for i in range(100):
	print(driver.read_tag(tag))
	sleep(.25)

**ERROR**
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "abpycomm/ab_comm/clx.py", line 405, in read_tag
    addr_data=self._target_cid,
  File "/usr/local/lib/python2.7/dist-packages/pycomm/cip/cip_base.py", line 590, in send_unit_data
    self._receive()
  File "/usr/local/lib/python2.7/dist-packages/pycomm/cip/cip_base.py", line 770, in _receive
    raise CommError(e)
pycomm.cip.cip_base.CommError: timed out

**Comment by crushndent** [comment]
Sorry - should have mentioned if someone can give me a hint, I am glad to look for the solution and contribute! I thought maybe generate_VSN().

**Comment by ruscito** [comment]
Hello @crushndent  the open method always generate a new CID and a new VSN

**Comment by crushndent** [comment]
For some reason it would not work and gave me the error above. The work around was to have each thread of execution open and close the connection more atomically and avoid two processes having the connection open at once.
