### ISSUE TITLE
CommError: must be str, not bytes

### ISSUE THREAD

**Issue by Karthikeyyan** [ruscito/pycomm#55]
I tried test_clx_comm.py example to connect a network PLC. But I get an error like this: 

TypeError                                 Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/pycomm/cip/cip_base.py in build_header(self, command, length)
    616             h = command                                 # Command UINT
--> 617             h += pack_uint(length)                      # Length UINT
    618             h += pack_dint(self._session)                # Session Handle UDINT

TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/pycomm/cip/cip_base.py in open(self, ip_address)
    785                 self.attribs['ip address'] = ip_address
--> 786                 if self.register_session() is None:
    787                     self._status = (13, "Session not registered")

/opt/conda/lib/python3.6/site-packages/pycomm/cip/cip_base.py in register_session(self)
    634         self._session = 0
--> 635         self._message = self.build_header(ENCAPSULATION_COMMAND['register_session'], 4)
    636         self._message += pack_uint(self.attribs['protocol version'])

/opt/conda/lib/python3.6/site-packages/pycomm/cip/cip_base.py in build_header(self, command, length)
    623         except Exception as e:
--> 624             raise CommError(e)
    625 

CommError: must be str, not bytes

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
<ipython-input-50-634919702ebe> in <module>
----> 1 c.open('10.21.150.175')

/opt/conda/lib/python3.6/site-packages/pycomm/cip/cip_base.py in open(self, ip_address)
    791             except Exception as e:
    792                 #self.clean_up()
--> 793                 raise CommError(e)
    794 
    795     def close(self):

CommError: must be str, not bytes

Few weeks back, I was able to connect and read values. But now Clueless!

**Comment by ruscito** [comment]
Unfortunately the lib has not been ported to python 3 yet
