### ISSUE TITLE
Reading multiple Timers

### ISSUE THREAD

**Issue by AndrewStuhr** [ruscito/pycomm#68]
Hello.  I'm not a PLC programmer, so the following terminology may be incorrect.

I'm able to read multiple words inside some registers.  For example, I can read F11:0 through F11:9 by using:   
c.read_tag('F11:0', 10).  

However, I'm unable to do the same with timers.  The following returns an error:
c.read_tag('T4:0', 10)

I can read individual elements of a timer, such as:
c.read_tag('T4:0.PRE')

Is there a way to read multiple timers in a single read request?  Thanks!

**Comment by ruscito** [comment]
Andrew,
timer like counter are complex objects holding more than one value. Unfortunately I couldn't find a way to read all the information in one shot nor there was any documentation available
